In [1]:
import numpy as np
import pandas as pd
import matplotlib as mat
import plotly as plot
import sklearn as sklearn
import string as string
import math

In [2]:
# set up
titanic = pd.read_csv("titanic.csv") 
titanic = titanic.rename({'home.dest': 'dest'},axis='columns')
def split(word): 
    return [char for char in word]
alphabet = set("abcdefghijklmnopqrstuwxyz")

In [3]:
print("problem 1: ", '\n')
partA = split("pneumonoultramicroscopicsilicovolcanoconiosisis")
partB = set(sorted(partA))
partC = alphabet - partB
partD = dict.fromkeys(partB,0);
for ch in partA:
    partD[ch] = partD[ch] + 1;
    
print("part A :", partA, '\n')
print("part B : ",partB, '\n')
print("part C : ", partC, '\n')
print("Dictionary D", partD, '\n')

problem 1:

part A : ['p', 'n', 'e', 'u', 'm', 'o', 'n', 'o', 'u', 'l', 't', 'r', 'a', 'm', 'i', 'c', 'r', 'o', 's', 'c', 'o', 'p', 'i', 'c', 's', 'i', 'l', 'i', 'c', 'o', 'v', 'o', 'l', 'c', 'a', 'n', 'o', 'c', 'o', 'n', 'i', 'o', 's', 'i', 's', 'i', 's']

part B :  {'v', 'a', 'n', 'u', 't', 's', 'i', 'e', 'c', 'm', 'l', 'o', 'p', 'r'}

part C :  {'d', 'y', 'b', 'g', 'k', 'z', 'j', 'h', 'q', 'w', 'f', 'x'}

Dictionary D {'v': 1, 'a': 2, 'n': 4, 'u': 2, 't': 1, 's': 5, 'i': 7, 'e': 1, 'c': 6, 'm': 2, 'l': 3, 'o': 9, 'p': 2, 'r': 2}

In [65]:
print("problem 2: ")
twoA = set("supercalifragilisticexpialidocious")

unionAB = sorted(partB.union(twoA))
print("part A : A U B :",unionAB, '\n')
AnotB = (twoA - partB)
BnotA = (partB - twoA)
print("A - B :", AnotB)
print("B - A :", BnotA)

AdeltaB = AnotB.union(BnotA)
print("A ∆ B :", AdeltaB)

A = twoA
B = partB
print("A - B = A intersection B complement")
if A - B == A.intersection(alphabet - B):
    print(True)
else:
    print(False)

print("A - B = A complement intsection B")
if A - B == (alphabet - A).intersection( B):
    print(True)
else:
    print(False)
    
print("\nDe Morgan’s law \n")
# Definition of De Morgan's law: ... The complement of the 
# union of two sets is equal to the intersection of their 
# complements and the complement of the intersection of two sets
# is equal to the union of their complements. These are called De Morgan's laws.
print("(A U B)' = A' ∩ B'")
print("(A U B)' = ", alphabet - B.union(A))
print(" A' ∩ B' = ",(alphabet - B).intersection(alphabet - A), ": True" )
print("(A U B)' = A' ∩ B'  : True\n" )
print("(A ∩ B)' = A' U B'")
print("(A ∩ B)' = ", (alphabet - B.intersection(A)))
print(" A' U B' = ", (alphabet - B).union(alphabet - A), ": True")

problem 2:
part A : A U B : ['a', 'c', 'd', 'e', 'f', 'g', 'i', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'x']

A - B : {'x', 'g', 'f', 'd'}
B - A : {'v', 'm', 'n'}
A ∆ B : {'x', 'v', 'm', 'd', 'n', 'g', 'f'}
A - B = A intersection B complement
True
A - B = A complement intsection B
False

De Morgan’s law

(A U B)' = A' ∩ B'
(A U B)' =  {'w', 'b', 'j', 'y', 'q', 'z', 'h', 'k'}
 A' ∩ B' =  {'w', 'b', 'y', 'j', 'q', 'z', 'h', 'k'} : True
(A U B)' = A' ∩ B'  : True

(A ∩ B)' = A' U B'
(A ∩ B)' =  {'w', 'x', 'm', 'b', 'n', 'f', 'j', 'y', 'q', 'z', 'd', 'h', 'k', 'g'}
 A' U B' =  {'w', 'm', 'n', 'j', 'y', 'q', 'z', 'd', 'h', 'g', 'x', 'b', 'f', 'k'} : True

In [66]:
print("problem 3: ")
#a
print("Part A : ",pd.isna(titanic.cabin).any(), '\n' )
#bcolumnsIndex
# print(titanic.columns)
data = titanic[['fare','survived']]

for row in data.index:
    if  data.loc[row, 'fare'] > titanic['fare'].min() or data.loc[row, 'survived'] == 0 or math.isnan(data.loc[row, 'survived']):
        data = data.drop(row, axis=0)

print("part B: " , len(data), '\n')

#c
print("part C : Name is\n",titanic.query('age == 18 and sex == "female" and survived == 1 and embarked == "C" and dest == "Haverford, PA / Cooperstown, NY"')['name'],'\n')

# Did anybody who didn’t pay any fare, had no cabin and didn’t have a destination
# survive?
#d
print("part D : number of people ",len(titanic.query('fare == 0 and survived == 1.0 and cabin.isnull() and dest.isnull()')))

problem 3:
Part A :  True

part B:  2

part C : Name is
 250    Ryerson, Miss. Emily Borie
Name: name, dtype: object

part D : number of people  1

In [67]:
print("problem 4:")

fareMean = (titanic['fare']).mean()
subsetFM = titanic.query('fare-@fareMean < .5')
# print(len(subsetFM))
print("part A : number of rows: ", len(subsetFM))
print(subsetFM.iloc[:3])
def FindNumberOfCommonStrings():
    ticket = titanic['ticket'].dropna().sort_values(ascending= True, na_position='first')
    prev = -1 
    curr = -1
    seen = 0
    count = 0
    for index in ticket.index:
        curr = ticket.loc[index]
        if prev != -1:
            if(prev == curr and seen != 1):
                seen = 1;
                count = count + 1
            else:
                seen = 0
        prev = curr 
    return count
    
print("part B : ", FindNumberOfCommonStrings())

def setUpLucky():
    l = []
    for index in titanic.index:
        row = titanic.loc[index]
        if row['pclass'] == 1 and row['fare'] > fareMean and row['survived'] == 0:
            l.append('unlucky')
        elif row['pclass'] > 1 and row['fare'] <= fareMean and row['survived'] == 1 :
            l.append('lucky')
        else:

         l.append('averageluck')
    return l
titanic = titanic.assign(luck = setUpLucky()) 
print("part C : \n", titanic['luck'].iloc[:4])

print("part D : ", titanic.groupby('luck').size())

problem 4:
part A : number of rows:  1005
    pclass  survived                                  name   sex   age  sibsp  \
5      1.0       1.0                   Anderson, Mr. Harry  male  48.0    0.0
7      1.0       0.0                Andrews, Mr. Thomas Jr  male  39.0    0.0
14     1.0       1.0  Barkworth, Mr. Algernon Henry Wilson  male  80.0    0.0

    parch  ticket   fare cabin embarked boat  body           dest
5     0.0   19952  26.55   E12        S    3   NaN   New York, NY
7     0.0  112050   0.00   A36        S  NaN   NaN    Belfast, NI
14    0.0   27042  30.00   A23        S    B   NaN  Hessle, Yorks
part B :  267
part C :
 0    averageluck
1    averageluck
2        unlucky
3        unlucky
Name: luck, dtype: object
part D :  luck
averageluck    956
lucky          277
unlucky         77
dtype: int64

In [68]:
print("problem 2: ")
print("Part A: ")
DF1 = {'id' : ['s01','s05','s06','s08'],
       'Name' : ['Julie','Carl','Luke','David'],
       'City' : ['Des Moines','Iowa city','Chicago','Minneapolis'],
       'Age' : ['25','34','29','45']}
DF2 = {'id' : ['s01','s08','s03','s04'],
       'Name' : ['Julie','David','Bradley','Nina'],
       'City' : ['Des Moines','Minneapolis','Tempe','Pittsburg'],
       'Age' : [3.25,3.4,3.3,4]}


df1 = pd.DataFrame(DF1, columns = ['id', 'Name', 'City','Age'])
df2 = pd.DataFrame(DF2, columns = ['id', 'Name', 'City','Age'])
df_left = pd.merge(df1, df2, on='id', how='left')
print(df_left,'\n')
print('Left join :  Takes each column from and labels it column_x and column_y to dictate which data frame that column came from. Then is creates a new data frame with all columns ordered x - y. Columns stay in order as the prevues data frames. By id dictates what data is merges. all of x is added but if a data frame y doesn’t have the corresponding id as x its replaced with NaN')
print("Part B: ")
df_right = pd.merge(df1, df2, on='id', how='right')
print(df_right,'\n')
print('Right join: Labels and orders all columns just as Left join but Id are now the Ids of data frame y. NaN is added to any x row that doesn’t line up with the id ')
print("Part C: ")
df_inner = pd.merge(df1, df2, on='id', how='inner')
print(df_inner,'\n')
print('Inner join is the interaction of the ids and the responding rows ')
print("Part D: ")
df_outer = pd.merge(df1, df2, on='id', how='outer')
print(df_outer,'\n')
print('Outer join is all data ids from data frame x and data frame y, or you could think of it as the union of left join and right join')

problem 2:
Part A:
    id Name_x       City_x Age_x Name_y       City_y  Age_y
0  s01  Julie   Des Moines    25  Julie   Des Moines   3.25
1  s05   Carl    Iowa city    34    NaN          NaN    NaN
2  s06   Luke      Chicago    29    NaN          NaN    NaN
3  s08  David  Minneapolis    45  David  Minneapolis   3.40

Left join :  Takes each column from and labels it column_x and column_y to dictate which data frame that column came from. Then is creates a new data frame with all columns ordered x - y. Columns stay in order as the prevues data frames. By id dictates what data is merges. all of x is added but if a data frame y doesn’t have the corresponding id as x its replaced with NaN
Part B:
    id Name_x       City_x Age_x   Name_y       City_y  Age_y
0  s01  Julie   Des Moines    25    Julie   Des Moines   3.25
1  s08  David  Minneapolis    45    David  Minneapolis   3.40
2  s03    NaN          NaN   NaN  Bradley        Tempe   3.30
3  s04    NaN          NaN   NaN     Nina    Pittsburg   4.00

Right join: Labels and orders all columns just as Left join but Id are now the Ids of data frame y. NaN is added to any x row that doesn’t line up with the id
Part C:
    id Name_x       City_x Age_x Name_y       City_y  Age_y
0  s01  Julie   Des Moines    25  Julie   Des Moines   3.25
1  s08  David  Minneapolis    45  David  Minneapolis   3.40

Inner join is the interaction of the ids and the responding rows
Part D:
    id Name_x       City_x Age_x   Name_y       City_y  Age_y
0  s01  Julie   Des Moines    25    Julie   Des Moines   3.25
1  s05   Carl    Iowa city    34      NaN          NaN    NaN
2  s06   Luke      Chicago    29      NaN          NaN    NaN
3  s08  David  Minneapolis    45    David  Minneapolis   3.40
4  s03    NaN          NaN   NaN  Bradley        Tempe   3.30
5  s04    NaN          NaN   NaN     Nina    Pittsburg   4.00

Outer join is all data ids from data frame x and data frame y, or you could think of it as the union of left join and right join